// <auto-generated />
namespace ZoomTwo.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class addattendees : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addattendees));
        
        string IMigrationMetadata.Id
        {
            get { return "202009141648332_add-attendees"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
